"""
Data Package for Final Fantasy VII: Rebirth
================================================================

This package contains all static data definitions and the game data
loader. Data is organized into logical modules:

Modules:
    item_tables.py
        Static item definitions organized by Archipelago classification.
        Contains PROGRESSION_ITEMS, USEFUL_ITEMS, FILLER_ITEMS, TRAP_ITEMS.
    
    location_tables.py
        Static location definitions organized by type.
        Contains STORY_LOCATIONS, VR_SUMMON_BATTLES, QUEST_LOCATIONS, etc.
    
    region_tables.py
        Region definitions and progression requirements.
        Contains REGIONS list, REGION_REQUIREMENTS, CHAPTER_REGIONS.
    
    game_loader.py
        GameDataManager class for loading exported game data.
        Handles parsing of JSON files from the exports/ subdirectory.

Subdirectories:
    exports/
        Contains raw JSON data exported from the game's UAsset files.
        These files are generated by the tools in /tools directory.

Key Exports:
    - get_game_data(): Get the global GameDataManager instance
    - FFVIIRItemData: NamedTuple for item definitions
    - FFVIIRLocationData: NamedTuple for location definitions
    - REGIONS, REGION_REQUIREMENTS: Region data
    - ItemType, LocationType: Enums for categorization
"""
from .game_loader import get_game_data, GameDataManager, ItemType, LocationType
from .item_tables import (
    PROGRESSION_ITEMS,
    USEFUL_ITEMS,
    SUMMON_MATERIA,
    FILLER_ITEMS,
    TRAP_ITEMS,
    FFVIIRItemData,
)
from .location_tables import (
    STORY_LOCATIONS,
    VR_SUMMON_BATTLES,
    QUEST_LOCATIONS,
    MINIGAME_LOCATIONS,
    FFVIIRLocationData,
)
from .region_tables import (
    REGIONS,
    REGION_REQUIREMENTS,
    CHAPTER_REGIONS,
    get_region_chapter,
)

__all__ = [
    # Game data loader
    "get_game_data",
    "GameDataManager",
    "ItemType",
    "LocationType",
    # Item tables
    "PROGRESSION_ITEMS",
    "USEFUL_ITEMS",
    "SUMMON_MATERIA",
    "FILLER_ITEMS",
    "TRAP_ITEMS",
    "FFVIIRItemData",
    # Location tables
    "STORY_LOCATIONS",
    "VR_SUMMON_BATTLES",
    "QUEST_LOCATIONS",
    "MINIGAME_LOCATIONS",
    "FFVIIRLocationData",
    # Region tables
    "REGIONS",
    "REGION_REQUIREMENTS",
    "CHAPTER_REGIONS",
    "get_region_chapter",
]
